# Generated by Django 4.0.4 on 2022-07-09 10:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Civilian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доход')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civilians', to='medieval_city.city', verbose_name='Город проживания')),
            ],
            options={
                'verbose_name': 'Горожанин',
                'verbose_name_plural': 'Горожане',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200, verbose_name='Название сословия')),
            ],
            options={
                'verbose_name': 'Сословие',
                'verbose_name_plural': 'Сословия',
            },
        ),
        migrations.CreateModel(
            name='Vassal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subordinate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seniors', to='medieval_city.civilian')),
            ],
        ),
        migrations.AddField(
            model_name='civilian',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='civilians', to='medieval_city.estate', verbose_name='Сословие'),
        ),
        migrations.AddField(
            model_name='civilian',
            name='senior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vassals', to='medieval_city.civilian', verbose_name='Сеньор'),
        ),
        migrations.AddField(
            model_name='civilian',
            name='vassal',
            field=models.ManyToManyField(blank=True, null=True, related_name='vassals', to='medieval_city.vassal', verbose_name='Вассал'),
        ),
    ]
